name: Dev tests

on:
  pull_request:
    branches:
      - dev

jobs:
  dev-tests:
    name: dev-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Run tests
        run: python test/test.py